# version: "3.9"

# services:
#   backend:
#     image: task-tracker-backend
#     container_name: backend
#     ports:
#       - "8000:8000"
#     restart: unless-stopped

#   frontend: 
#     image: task-tracker-frontend
#     container_name: frontend
#     ports:
#       - "3000:3000"
#     restart: unless-stopped
#     depends_on:
#       - backend
# Güncel
version: "3.9"

services:
  backend:
    image: bakiakgun/task-tracker-backend:1.0.0
    container_name: backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: bakiakgun/task-tracker-frontend:1.0.0
    container_name: frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend
